[package]
name = "coco"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# time format
chrono = "0.4"

git2 = "0.13"

# for cli usage
clap = "2.33.3"

# for git clone
tempdir = "0.3"

# parse for url
url = "2.2.0"

# cloc
tokei = "12.1.2"

plotters = "^0.3.0" # char

# serializing and deserializing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8" # for config parse
